os: linux
dist: bionic
arch: s390x
language: bash
jobs:
  include:
    - stage: build
      name: "stage naming"
      script: echo "Building first artifacts.........."
    - script: echo "Building second artifacts........."
    - script: eecho "Building third artifacts.........."
    - stage: test
      script: echo "Testing..........."
      script: echo "Testing first artifacts.........."
      script: echo "Testing second artifacts........."
      script: echo "Testing third artifacts.........."
    - stage: deploy
      script: echo "Deploying........."
      script: echo "Deploying first artifacts.........."
      script: echo "Deploying second artifacts........."
      script: echo "Deploying third artifacts.........."
