os: linux
dist: bionic
arch: s390x
language: bash
jobs:
  include:
    - stage: build
      script: echo "Building.........."
      script: "Building first artifacts.........."
      script: "Building second artifacts........."
      script: "Building third artifacts.........."
    - stage: test
      script: echo "Testing..........."
      script: "Testing first artifacts.........."
      script: "Testing second artifacts........."
      script: "Testing third artifacts.........."
    - stage: deploy
      script: echo "Deploying........."
      script: "Deploying first artifacts.........."
      script: "Deploying second artifacts........."
      script: "Deploying third artifacts.........."
