os: linux
dist: bionic
arch: s390x
language: bash
jobs:
  include:
    - stage: build
      script: echo "Building.........."
    - stage: test
      script: echo "Testing..........."
    - stage: deploy
      script: echo "Deploying........."
